import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/globals.scss";
import { QueryProvider } from "@/providers/QueryProvider";
import { AppProvider } from "@/context/AppContext";
import Header from "@/components/layout/Header"
import Footer from "@/components/layout/Footer"
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Estatio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <AppProvider>
              {children}
              <Toaster richColors position="top-center" />
          </AppProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
